'use strict';
/*
 * This file was autogenerated 
 * Any changes made here will be overriten!
 */

exports.EMOJI_PICKER_PATH = '.popouts';

exports.SETTINGS_CLASSES = undefined;
exports.SWITCH_CLASSES = 4549;
exports.FLEX_CHILD_CLASSES = 1106;
exports.FLEX_CLASSES = 1107;
exports.HEADER_CLASSES = 1205;
exports.SWITCH_ITEM_CLASSES = 1756;
exports.DIVIDER_ITEM_CLASSES = 4550;
exports.LABEL_ITEM_CLASSES = 4548;
exports.FONT_SIZE_CLASSES = 1158;
exports.CARD_CLASSES = 1170;
exports.EMOJI_BUTTON_CLASS = 5223;
exports.LOCAL_STORAGE_MODULE = 828;
exports.EMOJI_STORAGE_MODULE = 1307;
exports.SERVERS_STORAGE_MODULE = 45;
exports.SERVERS_PERMISSIONS_MODULE = 209;
exports.TRANSLATION_MODULE = 19;
exports.CUSTOM_EMOJI_STORAGE_MODULE = 1321;
exports.REACTION_EMOJI_CONVERTER = 1429;
