'use strict';
/*
 * This file was autogenerated 
 * Any changes made here will be overriten!
 */

exports.EMOJI_PICKER_PATH = '.popouts';

exports.SETTINGS_CLASSES = undefined;
exports.SWITCH_CLASSES = 4553;
exports.FLEX_CHILD_CLASSES = 1108;
exports.FLEX_CLASSES = 1109;
exports.HEADER_CLASSES = 1209;
exports.SWITCH_ITEM_CLASSES = 1760;
exports.DIVIDER_ITEM_CLASSES = 4554;
exports.LABEL_ITEM_CLASSES = 4552;
exports.FONT_SIZE_CLASSES = 1160;
exports.CARD_CLASSES = 1172;
exports.EMOJI_BUTTON_CLASS = 5227;
exports.LOCAL_STORAGE_MODULE = 830;
exports.EMOJI_STORAGE_MODULE = 1311;
exports.SERVERS_STORAGE_MODULE = 46;
exports.SERVERS_PERMISSIONS_MODULE = 208;
exports.TRANSLATION_MODULE = 19;
exports.CUSTOM_EMOJI_STORAGE_MODULE = 1325;
exports.REACTION_EMOJI_CONVERTER = 1433;
