'use strict';
/*
 * This file was autogenerated 
 * Any changes made here will be overriten!
 */

exports.EMOJI_PICKER_PATH = '.popouts';

exports.SETTINGS_CLASSES = 4831;
exports.SWITCH_CLASSES = 4528;
exports.FLEX_CHILD_CLASSES = 1103;
exports.FLEX_CLASSES = 1104;
exports.HEADER_CLASSES = 1205;
exports.SWITCH_ITEM_CLASSES = 1743;
exports.DIVIDER_ITEM_CLASSES = 4529;
exports.LABEL_ITEM_CLASSES = 4527;
exports.FONT_SIZE_CLASSES = 1159;
exports.CARD_CLASSES = 1170;
exports.EMOJI_BUTTON_CLASS = 5201;
exports.LOCAL_STORAGE_MODULE = 825;
exports.EMOJI_STORAGE_MODULE = 1307;
exports.SERVERS_STORAGE_MODULE = 45;
exports.SERVERS_PERMISSIONS_MODULE = 215;
exports.TRANSLATION_MODULE = 18;
exports.CUSTOM_EMOJI_STORAGE_MODULE = 1319;
exports.REACTION_EMOJI_CONVERTER = 1425;
